id: P5F722793
initial_creation_type: ocr
source_metadata:
  volumes:
    f6f2b5bde86e40d2ad90c2c52fec7d04:
      base_file: v039.txt
      image_group_id: I1PD95884
      title: སྒྲོལ་མའི་སྒྲུབ་ཐབས།
      total_pages: 1625
      volume_number: 39
